name: run-script
on: workflow_dispatch

jobs:
run:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v1
- name: script
run: ./package.sh
shell: bash
with:
password: ${{ secrets.ACCESS_TOKEN }}


